language: php
php:
  - '7.0'
  - '5.6'
  - '5.5'
  - '5.4'
  - 'hhvm'
env:
  global:
  - secure: "SswMLHRm6hsJnRBm9KsEj3t0nhqDO+UEfsU0H7IY4CoFlrWyumTxKAU7Enw5E7uF6RCiQiej37EdlMdn9txcCFlsiGrb/f4v7W27iyPDW3F8tUKkkXLw37ApoTInthiI/rmzKMgkism0ezeAy0JQTmyzoNDpZeq/ZirDtTUhuRdDIcveh9P3p2HUq/Ph1Iu9k9EZYkv/YRjNTa7azCMXkSIdiQBoEhpyweLuXZ5QlrHjgdhKxYKTwbL2NkKxbOFF3u/DNvsKXb/xAtge9fMtQORA+A2BZFSxUirygKrhfIoO+vAuxsV5LHy8omAkwNRePm9u13Q+wPjQ6wmy0PYfZ/8h9wp7k3Ct9Rx+JhS8ZzWXOhP36V9/JhxQyMGttwwkVFfW16P8d1WdY/Vbv+cRCMT4nSvwk5MTrjH44QGzfSkhcTpdN0oanzx7aBXHIFJboKHZ1+n8Q2b2KMKyOzplNwEoWT4jFUcOQgAUmFsPfAmYSRxbx948YjUXDU8xiL0EZzocRJ4DjlNqKdRdE3K43KAHOSG/qXSsEWlqtrpF3OqnWFau3LXtyMvnDWH/TdXuBnOxWWKz+vCPwZ2XB7MswPYpRlzYLnp+4/1QXJJjsuCnZuScPMhno3PEa7hT5zVJl6RfPcWRWcbbwrxooEVQpE+OQXGa7nsmZVB9fnjlXpw="
before_install:
  - sudo bash build-tools/travis_shell_before_install.sh
install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --no-interaction
  - mkdir -p build/docs
  - mkdir -p build/logs
script:
  - php vendor/bin/phpunit -c phpunit.xml.dist
after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
  - bash build-tools/travis_shell_after_success.sh
